### PR TITLE
Add Microsite Initial Scaffold

### LINKED ISSUE #12: Add microsite and docs for project

### PR DESCRIPTION
**Pull request by softinio**
# Summary

- Added Initial Microsite
- This is just the scaffold/template
- No content added yet, will be added under separate PRs
- Settings based on zio
- Using mdoc instead of tut as now supported by latest sbt microsite to avoid future migration

resolves #12 

# To Do

- Add content to microsite, created #20

### CODE REVIEW

**Comment by NeQuissimus** [comment]
You need to add a GitHub deploy key into `.travis.yaml`, otherwise `publishMicrosite` will fail. Check the scalaz-zio Travis file, I did all the work there.

**Comment by softinio** [comment]
> You need to add a GitHub deploy key into `.travis.yaml`, otherwise `publishMicrosite` will fail. Check the scalaz-zio Travis file, I did all the work there.

@NeQuissimus thanks for taking a look. I was trying to implement the deploy using the new github4s way as its seems a lot less complex: 

https://47deg.github.io/sbt-microsites/docs/publish-with-travis.html#publish-using-github4s

Any reason not to do it this way?

**Comment by softinio** [comment]
@NeQuissimus Trying to understand how you did it for zio. Whats this env variable that I see in the `.travis.yml`: 

```
${encrypted_316f730cabee_iv}
```
if easier ping me on gitter. Thanks!

**Comment by NeQuissimus** [comment]
Read through some of this:
https://github.com/NeQuissimus/test-and-stuff

Those variables are provided by Travis

**Comment by softinio** [comment]
@NeQuissimus Thats an awesome resource thanks for that.

**Comment by softinio** [comment]
@NeQuissimus Was going to setup publishing to sonatype whilst I am at it. Do you have the username and password for our org on sonatype I can use to set up travis with following your intructions? 

I assumed there are org level credentials I can use else I guess can try to get new ones. 

Thanks!

**Comment by NeQuissimus** [comment]
I have them, let me pop them in tomorrow.

**Comment by NeQuissimus** [comment]
```
secure: "ZvuaxdT/7sEAcG7+Jw2EmjL87xqxjFhS2IQ7rAcC1QVYtQt/cMBXbFjyxUxdm6yuKbWB/677e97wGgohX7LtvVfgNCBDeCc+0AHISjLSLY0dCcM9xtiQoXT8rQQtordYPjMsZZw9/LtF9XFwSQK4Lx+aeZl7H+VF5WE/fFmKl4W1c8oFHo2MvgHDKqWGuz1AfCdTLuLghBrEG1h21cfDi+tOrFXjk93CwmK63y3V3TXkbDLLJ6drmSwXIxZ9viNStYEDpTBOZ0yjevwuw/poKPMALwMjvIIogFnVNmvxY1KLfGufKlzG8sGdcLFTrKnin3t+It+6oW48GH+ZGnfJ33Ly/+Np8rMQpLxhIHZNZBZf4YOV0Gxp/54luhaL4Jm7RINelpWxjZImnyzhquEj4zxRIIlAGm/BJ/nf9G0vGdNxCIR6uwzUsl7E23UNItQ5bS2YSKYtCZy+HIru1zpP86ejw1zbE7fHTHIJyrGf+6sdfarJLVhJq/nU8F6TWKQHiGvvujqVqWyyRA4gBnv9SrTUDJsReZZELXJRfHl3RTUwKJR0GvxxNfgaR+P1ERvgffau/xsRzU3et2Dtl9eQEPGTP7jVBqKM13hS6uzQI0WoswxGfb49e2ztHNUXckxhaeVYCptUu/SGonJHryMTvxbWx60tzudVMpWFd0e3XVU="
secure: "WsMMGY+ztMqt1z0MZ1dr2hB/Mh9RbHyVxhCpbXTaMKdhUoDcOhHUaj/RdPlmoca4FatinPV0xT3SFqNUJR0M4GVCu7hXvQSn86rX7CPV6uG/a+eXoZC78ePdseFkqvmcJHyEJf0+ggzgsp+/PNGcKoOjc40P5tohPM3Wn+gUw5jdMfGzFzmTxlxL74xRD2dultGkifbCu6mDCT3NvcGJSB3JIZFva+LLE9QaaWAH0n6HKkVM6N9DIGEtLp/1/aJpm4uy7PUNnYcMV0l5/cs3Z0B6c2/KE7lF1xwmhhn2eq4qMiIT2RGaY4HbMLY884x/XP3Lq6/mus737H58FtFt8TinrDwImyvD4wgqP38/syVoH0HNR6xGM7EixEDtqVuVjc4u1ZJb7z8D6Z6sv0Wj6kWby/nIasLyePdeAKjiGGmoJiL1qm3bP6XS6P53ICKkgHQ4egZo3xW0z4gNB1CFm0ljkt57aqi8ewiBvTtgIrbPiFeNiGwxxF6uyCbJxAdn0+bPwKQvKr9WsMJ3HBoqdTmQcCvZwaswu2pHrGj/ToDWwJwPYWYkhY8oPfO109AZLLGPkL8eCLuElOBl+dsHbAe0N9MHn2gVYwWMH/tMAZ+3z0FFSJCH4sh+NBy1J0rqFV59FH8asRePQ2vdLeTFOvn5jtErPshgDYfFnPqhONo="
```

**Comment by softinio** [comment]
@NeQuissimus thanks for sending me the secrets. Do I use them as they are or have you send them to me in a secure format needs decryption before I can use them? If so format? 

@NeQuissimus @jdegoes In light of the demise of travisci and them laying all their staff off should I move to something like circleci whilst I am at it with this PR or are we sticking to travis for now? If you want me to make the move happy to put in the time to move other repos too if preferred.

**Comment by NeQuissimus** [comment]
You don't have to do anything but include those two lines in the `.travis.yml`.
Not sure about the "demise of TravisCI" :)

**Comment by softinio** [comment]
@NeQuissimus Ok thanks!

**Comment by softinio** [comment]
@NeQuissimus Just pushed a change to the travis and build configurations. I don't quite follow how the secret management for Travis works here but have tried to follow what you have in your repo. 

Can I trouble you to review what I have done and tell me if I am on right track? 

Your help really appreciated as new to travis and the way you have implemented this so appreciate you bridging my knowlesge gap. 

Let me know if easier to chat on gitter or other means.

**Comment by NeQuissimus** [comment]
Looks to me like you're on the right track. Note that the real fun begins when you merge into master :D Because parts of the build only run there :)

**Comment by softinio** [comment]
@NeQuissimus let the fun begin then. Can you approve this PR then if you are happy with it and lets see what happens on merge with master :-) Thx!

**Comment by NeQuissimus** [comment]
Done, I had not realized I had permissions to approve :)

**Comment by softinio** [comment]
@NeQuissimus thanks

**Pull request merged**
